# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Acquisition Pilot Guide
email: dap-18f@gsa.gov
description: "The Digital Acquisition Pilot is a fully-funded project lends a team of experts from the Presidential Innovation Fellows, 18F, and US Digital Service to an agency to train up a cadre of digital service experts."
baseurl: "/digitalaccelerator" # the subpath of your site, e.g. /blog
url: "https://pages.18f.gov/digitalaccelerator/" # the base hostname & protocol for your site
twitter_username: innovfellows

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE.md
  - about.yml
  - system-security-plan.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
